# Generated by Django 4.2.15 on 2024-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=15)),
                ('alias', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
